import Header from "@/(components)/Header/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";

const axiforma = localFont({
  src: "./fonts/Axiforma-Regular.woff2",
  variable:"--font-axiforma-sans",
  weight: "100 200 300 400 500 600 700 800 850 900",
});

export const metadata: Metadata = {
  title: "Clickup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${axiforma.variable}  antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}